### ISSUE TITLE
Cannot save without content despite what docs say

### ISSUE THREAD

**Issue by jscissr** [bennylope/django-addendum#11]
In the docs it [says](https://github.com/bennylope/django-addendum/blob/master/docs/index.rst#basic-usage):

> If you don’t add anything or you delete text, the site text will always revert to what is in the template.

However when I try to save with no text, I get an error that the field cannot be empty!

![image](https://cloud.githubusercontent.com/assets/4520820/11103326/01f62d30-88c2-11e5-9dbf-46c5abf8d073.png)

**Comment by bennylope** [comment]
I think the issue here is that wording in the docs. It should read, "if you delete a _snippet_" then it will revert. The text field itself should have content.
